#!/usr/bin/env bash


EXECUTABLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${EXECUTABLE_DIR}/.." && pwd)"

WORK_ROOT="${WORK_ROOT:-${REPO_ROOT}/work}"
RAW_READS_DIR="${RAW_READS_DIR:-${WORK_ROOT}/01_raw_reads}"
TRIM_DIR="${TRIM_DIR:-${WORK_ROOT}/02_trimmed_reads}"
ASSEMBLY_DIR="${ASSEMBLY_DIR:-${WORK_ROOT}/03_assemblies}"
QC_DIR="${QC_DIR:-${WORK_ROOT}/04_quast}"
TYPING_DIR="${TYPING_DIR:-${WORK_ROOT}/05_typing}"
AMR_DIR="${AMR_DIR:-${WORK_ROOT}/06_amrfinder}"
REFERENCE_DIR="${REFERENCE_DIR:-${WORK_ROOT}/07_reference}"
PHENIX_INPUT_DIR="${PHENIX_INPUT_DIR:-${WORK_ROOT}/08_phenix_inputs}"
PHENIX_OUTPUT_DIR="${PHENIX_OUTPUT_DIR:-${WORK_ROOT}/09_phenix}"
ALIGNMENT_DIR="${ALIGNMENT_DIR:-${WORK_ROOT}/10_alignments}"
PHYLOGENY_DIR="${PHYLOGENY_DIR:-${WORK_ROOT}/11_phylogeny}"
PLASMID_DIR="${PLASMID_DIR:-${WORK_ROOT}/12_plasmids}"

READS_MANIFEST="${READS_MANIFEST:-${REPO_ROOT}/data/manifests/reads_manifest.tsv}"
ASSEMBLIES_MANIFEST="${ASSEMBLIES_MANIFEST:-${ASSEMBLY_DIR}/assemblies.tsv}"
QC_APPROVED_IDS="${QC_APPROVED_IDS:-${REPO_ROOT}/data/manifests/assembly_qc_345.notebook_derived.txt}"
PHENIX_COHORT_IDS="${PHENIX_COHORT_IDS:-${REPO_ROOT}/data/manifests/phenix_331.notebook_derived.txt}"
CC25_IDS="${CC25_IDS:-${REPO_ROOT}/data/manifests/cc25_327.notebook_derived.txt}"
ST335_IDS="${ST335_IDS:-${REPO_ROOT}/data/manifests/st335_224.upstream_aliases.txt}"

ADAPTERS_FASTA="${ADAPTERS_FASTA:-${REPO_ROOT}/resources/adapters.fa}"
PHENIX_CONFIG="${PHENIX_CONFIG:-${REPO_ROOT}/resources/phenix_config.yml}"
REFERENCE_FASTA="${REFERENCE_FASTA:-${REPO_ROOT}/resources/CHF10J1_final_polished_reference.fasta}"
AMRFINDER_DB="${AMRFINDER_DB:-${REPO_ROOT}/resources/amrfinder_db/2024-05-02.2}"

BBDUK_THREADS="${BBDUK_THREADS:-8}"
SPADES_THREADS="${SPADES_THREADS:-12}"
QUAST_THREADS="${QUAST_THREADS:-12}"
AMRFINDER_THREADS="${AMRFINDER_THREADS:-1}"
REFERENCE_THREADS="${REFERENCE_THREADS:-8}"
PYPOLCA_THREADS="${PYPOLCA_THREADS:-12}"
PHENIX_MAX_FORKS="${PHENIX_MAX_FORKS:-8}"
GUBBINS_THREADS="${GUBBINS_THREADS:-32}"
RAXML_THREADS="${RAXML_THREADS:-32}"
SNP_DISTS_THREADS="${SNP_DISTS_THREADS:-12}"

MAX_ASSEMBLY_LENGTH="${MAX_ASSEMBLY_LENGTH:-5600000}"
MAX_CONTIGS="${MAX_CONTIGS:-300}"

QUAST_LENGTH_METRIC="${QUAST_LENGTH_METRIC:-}"
QUAST_CONTIG_METRIC="${QUAST_CONTIG_METRIC:-}"

AMRFINDER_USE_PLUS="${AMRFINDER_USE_PLUS:-0}"

PHENIX_CONTAINER="${PHENIX_CONTAINER:-flashton/phenix-threaded-samtools:latest}"
REFERENCE_HEADERS_FILE="${REFERENCE_HEADERS_FILE:-${REPO_ROOT}/environment/phenix_reference_headers.txt}"

TREE_MODEL="${TREE_MODEL:-GTR+G}"
TREE_BOOTSTRAPS="${TREE_BOOTSTRAPS:-1000}"
TREE_SEED="${TREE_SEED:-12345}"

ALLOW_EXISTING_OUTPUTS="${ALLOW_EXISTING_OUTPUTS:-0}"
