publication <- new.env(parent = globalenv())
sys.source(file.path(ROOT, "scripts", "lib", "publication.R"), envir = publication)
tr <- ape::read.tree(file.path(DATA, "trees", "CC25_publication_tree.nwk"))
m <- read.csv(file.path(DATA, "data_clean", "CC25_exact_tip_metadata.csv"), check.names = FALSE)
view <- publication$prepare_tree_view(tr, m)
save_drawing(publication$circular_draw(view, list()), "Figure_3A_CC25", 210, 165)
save_native(native$build_st335_main(d, cfg), "Figure_4_ST335_genomic_heatmap", "main")
save_native(native$build_panel_index(d, cfg, "CC25"), "Figure_S05_CC25_panel_index")
save_native(native$build_panel_index(d, cfg, "ST335"), "Figure_S19_ST335_panel_index")
ids <- unique(d$panels$panel_id[d$panels$population == "CC25"])
figure_numbers <- c(6:11, 13:18)
for (i in seq_along(ids))
  save_native(native$build_tree_detail(d, cfg, "CC25", ids[i]), sprintf("Figure_S%02d_%s_labelled_tree", figure_numbers[i], ids[i]))
file.copy(file.path(OUT, "supplementary", "Figure_S10_CC25-05_labelled_tree.tiff"),
  file.path(OUT, "supplementary", "Figure_S12_CC25-05_repeated_plate.tiff"), overwrite = TRUE)
