dir.create("environment", recursive = TRUE, showWarnings = FALSE)
dir.create("results/environment", recursive = TRUE, showWarnings = FALSE)
session_record <- capture.output(sessionInfo())
writeLines(session_record, "environment/sessionInfo.txt")
writeLines(session_record, "results/environment/sessionInfo.txt")
p <- as.data.frame(installed.packages()[, c("Package", "Version", "Built")], stringsAsFactors = FALSE)
write.csv(p, "environment/R_packages.csv", row.names = FALSE)
write.csv(p, "results/environment/R_packages.csv", row.names = FALSE)
if (requireNamespace("renv", quietly = TRUE) && "--lock" %in% commandArgs(trailingOnly = TRUE))
  renv::snapshot(lockfile = "environment/renv.lock", type = "all", prompt = FALSE)
